---
openapi: 3.0.1
info:
  title: DataBridge Product Service API
  version: v1
  description: API for managing products, categories, and inventory
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
paths:
  "/api/v1/categories":
    get:
      summary: Lists categories
      tags:
      - Categories
      parameters:
      - name: include_inactive
        in: query
        required: false
        schema:
          type: boolean
      - name: parent_id
        in: query
        required: false
        schema:
          type: integer
      - name: root
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: categories found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    parent_id:
                      type: integer
                      nullable: true
                    active:
                      type: boolean
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
    post:
      summary: Creates a category
      tags:
      - Categories
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: category created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  parent_id:
                    type: integer
                    nullable: true
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: New Category
                description:
                  type: string
                  example: Category description
                parent_id:
                  type: integer
                  example: 1
                  nullable: true
                active:
                  type: boolean
                  example: true
              required:
              - name
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a category
      tags:
      - Categories
      responses:
        '200':
          description: category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  parent_id:
                    type: integer
                    nullable: true
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  subcategories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                        parent_id:
                          type: integer
                        active:
                          type: boolean
        '404':
          description: category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Updates a category
      tags:
      - Categories
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: category updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  parent_id:
                    type: integer
                    nullable: true
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Category
                description:
                  type: string
                  example: Updated description
                parent_id:
                  type: integer
                  example: 2
                  nullable: true
                active:
                  type: boolean
                  example: true
    delete:
      summary: Deactivates a category
      tags:
      - Categories
      security:
      - bearer_auth: []
      responses:
        '204':
          description: category deactivated
        '404':
          description: category not found
  "/api/v1/products/{product_id}/inventory":
    parameters:
    - name: product_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves inventory for a product
      tags:
      - Inventories
      security:
      - bearer_auth: []
      responses:
        '200':
          description: inventory found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                  low_stock_threshold:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Updates inventory for a product
      tags:
      - Inventories
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: inventory updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                  low_stock_threshold:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 100
                low_stock_threshold:
                  type: integer
                  example: 10
  "/api/v1/inventories/batch":
    post:
      summary: Updates inventory in batch
      tags:
      - Inventories
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: inventories updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        quantity:
                          type: integer
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        errors:
                          type: array
                          items:
                            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                inventories:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                    required:
                    - product_id
                    - quantity
              required:
              - inventories
  "/api/v1/products":
    get:
      summary: Lists products
      tags:
      - Products
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: category_id
        in: query
        required: false
        schema:
          type: integer
      - name: price_min
        in: query
        required: false
        schema:
          type: number
      - name: price_max
        in: query
        required: false
        schema:
          type: number
      - name: sort_by
        in: query
        required: false
        schema:
          type: string
      - name: sort_direction
        in: query
        required: false
        enum:
        - asc
        - desc
        schema:
          type: string
        description: ":\n * `asc` \n * `desc` \n "
      - name: include_inactive
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: products found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    sku:
                      type: string
                    price:
                      type: number
                      format: float
                    active:
                      type: boolean
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
    post:
      summary: Creates a product
      tags:
      - Products
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  sku:
                    type: string
                  price:
                    type: number
                    format: float
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: New Product
                description:
                  type: string
                  example: Product description
                sku:
                  type: string
                  example: PRD-001
                price:
                  type: number
                  format: float
                  example: 29.99
                active:
                  type: boolean
                  example: true
              required:
              - name
              - sku
              - price
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a product
      tags:
      - Products
      responses:
        '200':
          description: product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  sku:
                    type: string
                  price:
                    type: number
                    format: float
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  inventory:
                    type: object
                    properties:
                      id:
                        type: integer
                      quantity:
                        type: integer
                      low_stock_threshold:
                        type: integer
        '404':
          description: product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Updates a product
      tags:
      - Products
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: product updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  sku:
                    type: string
                  price:
                    type: number
                    format: float
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Product
                description:
                  type: string
                  example: Updated description
                price:
                  type: number
                  format: float
                  example: 39.99
                active:
                  type: boolean
                  example: true
    delete:
      summary: Deactivates a product
      tags:
      - Products
      security:
      - bearer_auth: []
      responses:
        '204':
          description: product deactivated
        '404':
          description: product not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3002
